name: 'finops'
version: '1.0.0'
config-version: 2

profile: 'finops'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finops:
    staging:
      +materialized: view
    marts:
      +materialized: table
      mart_cashflow_daily:
        +materialized: incremental
        +unique_key: date
      mart_cashflow_monthly:
        +materialized: incremental
        +unique_key: month
      mart_budget_vs_actual:
        +materialized: incremental
        +unique_key: "month || '_' || category_id::string"
      mart_recurring:
        +materialized: incremental
        +unique_key: "merchant_norm || '_' || category_norm"
      mart_anomalies:
        +materialized: incremental
        +unique_key: id
      mart_forecasts:
        +materialized: incremental
        +unique_key: "forecast_date || '_' || category_id::string"

seeds:
  finops:
    +schema: ref
    categories:
      +column_types:
        category_id: integer
        parent_id: integer
    merchant_rules:
      +column_types:
        rule_id: integer
        priority: integer
    fx_rates:
      +column_types:
        date: date
        usd_to_eur: decimal(10,6)
        usd_to_gbp: decimal(10,6)

vars:
  # Add any variables you want to set globally for your project
  currency: "USD"
  timezone: "UTC"

# Configuring models
# In your model files, you can also use the config() function to define
# the table schema and materialization type. 